# Generated by Django 2.0.3 on 2018-04-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyKitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mykitchen',
            old_name='name',
            new_name='user',
        ),
    ]
