# Generated by Django 2.0.3 on 2018-04-29 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyKitchen', '0002_auto_20180429_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykitchen',
            name='itemID',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
