# Generated by Django 2.0.3 on 2018-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKitchen', '0003_mykitchen_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykitchen',
            name='id',
        ),
        migrations.AlterField(
            model_name='mykitchen',
            name='itemID',
            field=models.CharField(max_length=50, primary_key='True'),
        ),
        migrations.AlterField(
            model_name='mykitchen',
            name='user',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
