# Generated by Django 2.0.3 on 2018-05-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyKitchen', '0004_auto_20180508_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mykitchen',
            old_name='itemID',
            new_name='food_ID',
        ),
    ]
