# Generated by Django 2.0.3 on 2018-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('user', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('food_ID', models.CharField(max_length=50, primary_key='True')),
            ],
        ),
    ]
