# Generated by Django 2.0.3 on 2018-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_ID', models.IntegerField(primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('longevity', models.IntegerField(default=0)),
                ('longevityType', models.CharField(max_length=50)),
                ('storageType', models.CharField(max_length=50)),
                ('storageTips', models.CharField(max_length=255)),
            ],
        ),
    ]
