# Generated by Django 2.0.3 on 2018-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_auto_20180429_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.AddField(
            model_name='food',
            name='food_ID',
            field=models.IntegerField(default=1, primary_key='True', serialize=False),
            preserve_default=False,
        ),
    ]
