# Generated by Django 2.0.3 on 2018-06-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.IntegerField(primary_key='True', serialize=False, unique='True')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=25, unique='True')),
                ('account_creation_date', models.DateField(auto_now_add=True)),
                ('account_last_modified', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
